;

CREATE USER IF NOT EXISTS "SA" SALT '8e2a3a88c972f437' HASH 'b5a6d5f6d1ebe7fe4244a90a7c270586549503f73ba244527733a2511b58d308' ADMIN;

CREATE SEQUENCE "PUBLIC"."SEQ_USER" START WITH 1 BELONGS_TO_TABLE;

CREATE CACHED TABLE "PUBLIC"."T_USER"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SEQ_USER" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SEQ_USER",
    "STATUS" VARCHAR(3) NOT NULL,
	"IDENTIFICATION_NUMBER" VARCHAR(10) NOT NULL,
	"NAME" VARCHAR(30) NOT NULL,
	"LASTNAME" VARCHAR(30) NOT NULL,
	"PHONE_NUMBER" VARCHAR(10) NOT NULL
);

ALTER TABLE "PUBLIC"."T_USER" ADD CONSTRAINT "PUBLIC"."USER_PK" PRIMARY KEY("ID");

INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-6596331', 'Chris', 'James', '579855222');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-5693654', 'Lex', 'Lutor', '');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-9636589', 'Patrick', 'Stwear', '');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-1798632', 'Oliver', 'Atom', '');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-5678900', 'Peter', 'Parker', '');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-7725632', 'Bruno', 'Mars', '');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-5623125', 'Michael', 'Jackson', '');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-6950215', 'Luigi', 'Martineli', '');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-2753201', 'Marck', 'Robson', '');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-5789562', 'Piero', 'Gomez', '');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-8523201', 'Joseph', 'Rochi', '');
INSERT INTO T_USER VALUES (NULL, 'ACT', 'ID-4012895', 'Sagmor', 'Saga', '');

--

CREATE SEQUENCE "PUBLIC"."SEQ_COURSE" START WITH 1 BELONGS_TO_TABLE;

CREATE CACHED TABLE "PUBLIC"."T_COURSE"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SEQ_COURSE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SEQ_COURSE",
    "STATUS" VARCHAR(3) NOT NULL,
	"CODE" VARCHAR(6) NOT NULL,
	"NAME" VARCHAR(30) NOT NULL,
	"DESCRIPTION" VARCHAR(100) NOT NULL,
	"PRICE" DECIMAL(9, 2) NOT NULL,
	"BY_DEFAULT" BOOLEAN NOT NULL
);

ALTER TABLE "PUBLIC"."T_COURSE" ADD CONSTRAINT "PUBLIC"."COURSE_PK" PRIMARY KEY("ID");

INSERT INTO T_COURSE VALUES (NULL, 'ACT', 'CR-001', 'Software Engineering', 'Software Engineering', 10.60, TRUE);
INSERT INTO T_COURSE VALUES (NULL, 'ACT', 'CR-002', 'Java Language', 'Java Language', 200.96, TRUE);
INSERT INTO T_COURSE VALUES (NULL, 'ACT', 'CR-003', 'PostgreSQL', 'PostgreSQL', 150.96, TRUE);
INSERT INTO T_COURSE VALUES (NULL, 'ACT', 'CR-004', 'React', 'React', 220.88, TRUE);
INSERT INTO T_COURSE VALUES (NULL, 'ACT', 'CR-005', 'Angular', 'Angular', 250.12, TRUE);
INSERT INTO T_COURSE VALUES (NULL, 'ACT', 'CR-006', 'Net Core', 'Net Core', 220.50, TRUE);
INSERT INTO T_COURSE VALUES (NULL, 'ACT', 'CR-007', 'Redis', 'Redis', 100.25, TRUE);
INSERT INTO T_COURSE VALUES (NULL, 'ACT', 'CR-008', 'WebFlux', 'WebFlux', 352.98, TRUE);
INSERT INTO T_COURSE VALUES (NULL, 'ACT', 'CR-009', 'Spring Boot', 'Spring Boot', 205.23, TRUE);
INSERT INTO T_COURSE VALUES (NULL, 'ACT', 'CR-010', 'Chat GPT', 'Chat GPT', 362.79, TRUE);

--

CREATE SEQUENCE "PUBLIC"."SEQ_REGISTER" START WITH 1 BELONGS_TO_TABLE;

CREATE CACHED TABLE "PUBLIC"."T_REGISTER"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SEQ_REGISTER" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SEQ_REGISTER",
    "STATUS" VARCHAR(3) NOT NULL,
	"USER_ID" INTEGER NOT NULL,
	"REGISTER_DATE" DATE NULL
);

ALTER TABLE "PUBLIC"."T_REGISTER" ADD CONSTRAINT "PUBLIC"."REGISTER_PK" PRIMARY KEY("ID");

INSERT INTO T_REGISTER VALUES (NULL, 'ACT', 1, CURRENT_DATE());

--

CREATE SEQUENCE "PUBLIC"."SEQ_REGISTRATION" START WITH 1 BELONGS_TO_TABLE;

CREATE CACHED TABLE "PUBLIC"."T_COURSE_REGISTRATION"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SEQ_REGISTRATION" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SEQ_REGISTRATION",
	"STATUS" VARCHAR(3) NOT NULL,
	"REGISTER_ID" INTEGER NOT NULL,
	"COURSE_ID" INTEGER NOT NULL,
	"START_DATE" DATE NOT NULL,
	"END_DATE" DATE NOT NULL
);

INSERT INTO T_COURSE_REGISTRATION VALUES (NULL, 'ACT', 1, 1, CURRENT_DATE(), CURRENT_DATE());